# Example configuration for Fedora Messaging
# For complete documentation check
# https://fedora-messaging.readthedocs.io/en/latest/configuration.html.

amqp_url = "amqps://fedora:@rabbitmq.fedoraproject.org/%2Fpublic_pubsub"

publish_exchange = "amq.topic"
passive_declares = false

callback = "joystick.consumers.fedora_messaging_consumer:JoyStickController"

[tls]
ca_cert = "/etc/fedora-messaging/cacert.pem"
keyfile = "/etc/fedora-messaging/fedora-key.pem"
certfile = "/etc/fedora-messaging/fedora-cert.pem"

[client_properties]
app = "joystick"

[exchanges."amq.topic"]
type = "topic"
durable = true
auto_delete = false
arguments = {}

[queues."6d0c4921-a865-4b10-8d13-47196a66289c"]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[[bindings]]
queue = "6d0c4921-a865-4b10-8d13-47196a66289c"
exchange = "amq.topic"
routing_keys = ["#"]

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "DEBUG"
handlers = ["console"]

# joystick consumer configuration
[consumer_config]
topic_prefix = 'org.fedoraproject'
environment = 'prod'
regions = ["us-east-2"]
aws_access_key_id = ''
aws_secret_access_key = ''
